---
metasheet: metasheet.csv
ref: viper/ref.yaml
assembly: 'hg19'

## Is your library stranded? options are [true, false]
stranded: true
# Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: 'fr-firststrand'

##PARAMS
## Sample-Sample Heatmap params
RPKM_threshold: 1.0
min_num_samples_expressing_at_threshold: 1

## Filters out "SNO" and "MIR" RNA, options are [true,false]
filter_mirna: true

## Number of genes to be represented in the Sample-Sample, Sample-Feature, and PCA plots
numgenes_plots: 1000

## Plotting param for Sample-Feature Heatmap. Number represents number of kmeans in heatmap, 0 will output a hierarchical clustering heatmap, finally, a list of numbers "0,2,4" will output all three heatmaps in the same pdf (NOTE: be sure to include the "quotes" ONLY when giving a list!  Do not give quotes when it's just a single number)
num_kmeans_clust: 1

#Turn on the following if you want a genome wide snp scan in addition to chr6 scan
# possible value are [true,false]
snp_scan_genome: false

#Uncomment the following if you want to perform a scan of viral dna on your samples
# possible value are [true,false]
virus_dna_scan: false

# If this flag is on, you must have a metasheet column called batch with at least 2 samples per batch
## Options are [false, true]
batch_effect_removal: false

## adjpval for a gene to be considered differentially expressed and be included in GOterm analysis
goterm_adjpval_cutoff: 0.1
## Number of GOterms in plot
numgoterms: 5
## Number of KEGG pathways in plot (note there is no cutoff herre because the KEGG module takes in full population statistics)
kegg_analysis: false
numkeggpathways: 5

#GSEA analysis- perform gsea analysis
gsea_analysis: false
#Path to GSEA gene set enrichment db
gsea_db: viper/static/gsea/msigdb.v6.1.symbols.gmt

#FGSEA analysis- perform Fgsea analysis
fgsea_analysis: false
#Path to FGSEA gene set enrichment db
fgsea_db: viper/static/fgsea/h.all.v6.2.symbols.gmt

#Uncomment the following line to perform TIMER (immunology) analysis. refer to 
#README.md
#cancer_type: 'sarc'

#Uncomment the following line to perform a TRUST (cdr3) analysis.  refer to README.md
cdr3_analysis: false

#Perform RSEM analysis
rsem_analysis: false
TPM_threshold: 1.0

#Perform HLA typing analysis using optitype
HLA_analysis: false

samples:
  #FOR SINGLE-END samples
  SAMPLE1:
    - /path/to/sample1.fastq.gz
  #FOR PAIRED-END samples--WARNING: DON'T mix single-end samples w/ paired-end
  SAMPLE1:
    - /path/to/sample1_R1.fastq.gz
    - /path/to/sample1_R2.fastq.gz
  #SAMPLE2:
  #ETC...
